# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

#- task: Npm@1
#  inputs:
#    command: 'custom'
#    customCommand: 'install newman -g'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'install -g newman-reporter-htmlextra'

- task: CmdLine@2
  inputs:
    script: newman run Ipf.CusApp.Backend-Public-uat.postman_collection.json -r htmlextra --reporters cli,junit,json,htmlextra --reporter-junit-export "junitReport.xml" --reporter-htmlextra-export "TestReport.html"
    displayName: 'Run Tests'

- task: CopyFiles@2
  inputs:
#    Contents: '*.html'
    Contents: 'TestReport.html'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #ArtifactName: 'OutputTestNGResultsXML'
    publishLocation: 'Container'
